---
deployment:
  tasks:
    - export DEPLOYPATH=/home/payibgdj/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp process-form.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
   